return {
	config=
	{
		[1]=
		{
			line = 1,
			act_type = "normal",
			ID = 1,
			title = "FREE GIFT",
			order = 4001,
			is_on_off = 1,
			beginTime = -1,
			endTime = -1,
			showType = "prefab",
			gotoUI = {"act_fb_guide","panel"},
			isRedDaily = 0,
		},
		[2]=
		{
			line = 2,
			act_type = "normal",
			ID = 2,
			title = "Kode Penukaran",
			order = 5001,
			is_on_off = 1,
			beginTime = -1,
			endTime = -1,
			showType = "prefab",
			gotoUI = {"act_gift_exchange","panel"},
			isRedDaily = 0,
		},
		[3]=
		{
			line = 3,
			act_type = "normal",
			ID = 3,
			title = "Kartu Bulanan",
			order = 3001,
			is_on_off = 1,
			beginTime = -1,
			endTime = -1,
			showType = "prefab",
			gotoUI = {"act_yk","panel"},
			isRedDaily = 1,
		},
		[4]=
		{
			line = 4,
			act_type = "normal",
			ID = 4,
			title = "Hadiah\nKuesioner",
			order = 2001,
			is_on_off = 1,
			beginTime = -1,
			endTime = -1,
			showType = "prefab",
			gotoUI = {"act_suggested_ollection","panel"},
			isRedDaily = 1,
		},
		[5]=
		{
			line = 5,
			act_type = "normal",
			ID = 5,
			title = "Bonus Menang",
			order = 1001,
			is_on_off = 1,
			beginTime = -1,
			endTime = -1,
			showType = "prefab",
			gotoUI = {"act_yjfl","panel"},
			isRedDaily = 1,
		},
		[6]=
		{
			line = 6,
			act_type = "normal",
			ID = 6,
			title = "Bonus Game",
			order = 2002,
			is_on_off = 1,
			condi_key = "act_yxfl_20220322",
			beginTime = -1,
			endTime = -1,
			showType = "prefab",
			gotoUI = {"act_yxfl","panel"},
			isRedDaily = 1,
		},
	},
}