//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaFramework_SDKManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaFramework.SDKManager), typeof(Manager));
		L.RegFunction("Init", Init);
		L.RegFunction("Login", Login);
		L.RegFunction("FBLogin", FBLogin);
		L.RegFunction("FBLogOut", FBLogOut);
		L.RegFunction("LoginOut", LoginOut);
		L.RegFunction("Relogin", Relogin);
		L.RegFunction("Pay", Pay);
		L.RegFunction("PostPay", PostPay);
		L.RegFunction("SetPayCallback", SetPayCallback);
		L.RegFunction("SetPostPayCallback", SetPostPayCallback);
		L.RegFunction("Share", Share);
		L.RegFunction("ShowAccountCenter", ShowAccountCenter);
		L.RegFunction("SendToSDKMessage", SendToSDKMessage);
		L.RegFunction("AddHandleScanFileCallback", AddHandleScanFileCallback);
		L.RegFunction("ScanFile", ScanFile);
		L.RegFunction("SaveImageToPhotosAlbum", SaveImageToPhotosAlbum);
		L.RegFunction("SaveVideoToPhotosAlbum", SaveVideoToPhotosAlbum);
		L.RegFunction("OpenPhotoAlbums", OpenPhotoAlbums);
		L.RegFunction("OpenApp", OpenApp);
		L.RegFunction("AddHandleOpenAppResultCallback", AddHandleOpenAppResultCallback);
		L.RegFunction("OnUpdCityName", OnUpdCityName);
		L.RegFunction("OnGPS", OnGPS);
		L.RegFunction("GetLatitude", GetLatitude);
		L.RegFunction("GetLongitude", GetLongitude);
		L.RegFunction("GetLocation", GetLocation);
		L.RegFunction("OnRecord", OnRecord);
		L.RegFunction("OnPlayRecordFinish", OnPlayRecordFinish);
		L.RegFunction("GetDeviceID", GetDeviceID);
		L.RegFunction("GetDeeplink", GetDeeplink);
		L.RegFunction("GetPushDeviceToken", GetPushDeviceToken);
		L.RegFunction("RunVibrator", RunVibrator);
		L.RegFunction("CallUp", CallUp);
		L.RegFunction("StartGPS", StartGPS);
		L.RegFunction("QueryCityName", QueryCityName);
		L.RegFunction("QueryGPS", QueryGPS);
		L.RegFunction("GetRecordTime", GetRecordTime);
		L.RegFunction("StartRecord", StartRecord);
		L.RegFunction("StopRecord", StopRecord);
		L.RegFunction("PlayRecord", PlayRecord);
		L.RegFunction("StopPlayRecord", StopPlayRecord);
		L.RegFunction("ShowProductRate", ShowProductRate);
		L.RegFunction("GetCanLocation", GetCanLocation);
		L.RegFunction("GetCanVoice", GetCanVoice);
		L.RegFunction("GetCanCamera", GetCanCamera);
		L.RegFunction("GetCanPushNotification", GetCanPushNotification);
		L.RegFunction("OpenLocation", OpenLocation);
		L.RegFunction("OpenVoice", OpenVoice);
		L.RegFunction("OpenCamera", OpenCamera);
		L.RegFunction("GotoSetScene", GotoSetScene);
		L.RegFunction("LoadFile", LoadFile);
		L.RegFunction("ForceQuit", ForceQuit);
		L.RegFunction("GGInit", GGInit);
		L.RegFunction("AddGoogleComCallback", AddGoogleComCallback);
		L.RegFunction("AddSkuStateFromPurchaseCallback", AddSkuStateFromPurchaseCallback);
		L.RegFunction("AddOnGGBuyResultCallback", AddOnGGBuyResultCallback);
		L.RegFunction("GGBuy", GGBuy);
		L.RegFunction("OnGGConsumeInappPurchase", OnGGConsumeInappPurchase);
		L.RegFunction("OnGGRefreshPurchasesAsync", OnGGRefreshPurchasesAsync);
		L.RegFunction("OnGGQuerySkuDetailsAsync", OnGGQuerySkuDetailsAsync);
		L.RegFunction("OnGGIsReady", OnGGIsReady);
		L.RegFunction("OnGGConnection", OnGGConnection);
		L.RegFunction("OnGGIsPurchased", OnGGIsPurchased);
		L.RegFunction("OnGGCanPurchased", OnGGCanPurchased);
		L.RegFunction("OnGGBillingFlowInProcess", OnGGBillingFlowInProcess);
		L.RegFunction("OnGGSkuTitle", OnGGSkuTitle);
		L.RegFunction("OnGGSkuPrice", OnGGSkuPrice);
		L.RegFunction("OnGGSkuDescription", OnGGSkuDescription);
		L.RegFunction("OnGGLogEvent", OnGGLogEvent);
		L.RegFunction("OnGGReview", OnGGReview);
		L.RegFunction("OnGGLaunchReview", OnGGLaunchReview);
		L.RegFunction("OnGGSignIn", OnGGSignIn);
		L.RegFunction("OnGGSignOut", OnGGSignOut);
		L.RegFunction("OnGGRevokeAccess", OnGGRevokeAccess);
		L.RegFunction("GetAFConversionJsonData", GetAFConversionJsonData);
		L.RegFunction("AddOnAFConversionCallback", AddOnAFConversionCallback);
		L.RegFunction("OnAFInit", OnAFInit);
		L.RegFunction("OnAFStart", OnAFStart);
		L.RegFunction("OnAFLogEvent", OnAFLogEvent);
		L.RegFunction("GetMessagingData", GetMessagingData);
		L.RegFunction("AddFirebaseComCallback", AddFirebaseComCallback);
		L.RegFunction("OnSubscribeToTopic", OnSubscribeToTopic);
		L.RegFunction("OnUnsubscribeFromTopic", OnUnsubscribeFromTopic);
		L.RegFunction("SendUpstream", SendUpstream);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.Init(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Login(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.Login(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FBLogin(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.FBLogin(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FBLogOut(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.FBLogOut(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoginOut(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.LoginOut(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Relogin(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.Relogin(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Pay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.Pay(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PostPay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.PostPay(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetPayCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.SetPayCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetPostPayCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.SetPostPayCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Share(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.Share(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowAccountCenter(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.ShowAccountCenter(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendToSDKMessage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SendToSDKMessage(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddHandleScanFileCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.AddHandleScanFileCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ScanFile(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.ScanFile(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SaveImageToPhotosAlbum(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SaveImageToPhotosAlbum(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SaveVideoToPhotosAlbum(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SaveVideoToPhotosAlbum(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OpenPhotoAlbums(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			obj.OpenPhotoAlbums();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OpenApp(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			obj.OpenApp(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddHandleOpenAppResultCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.AddHandleOpenAppResultCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnUpdCityName(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OnUpdCityName(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGPS(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OnGPS(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLatitude(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			float o = obj.GetLatitude();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLongitude(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			float o = obj.GetLongitude();
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLocation(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string o = obj.GetLocation();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnRecord(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OnRecord(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPlayRecordFinish(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OnPlayRecordFinish(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetDeviceID(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string o = obj.GetDeviceID(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetDeeplink(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string o = obj.GetDeeplink();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetPushDeviceToken(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string o = obj.GetPushDeviceToken();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RunVibrator(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			long arg0 = LuaDLL.tolua_checkint64(L, 2);
			obj.RunVibrator(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CallUp(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.CallUp(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartGPS(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.StartGPS(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int QueryCityName(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			obj.QueryCityName(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int QueryGPS(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.QueryGPS(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetRecordTime(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			int o = obj.GetRecordTime();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartRecord(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			int o = obj.StartRecord(arg0, arg1);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopRecord(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.StopRecord(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlayRecord(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			int o = obj.PlayRecord(arg0, arg1);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopPlayRecord(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			obj.StopPlayRecord();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowProductRate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.ShowProductRate(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCanLocation(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			int o = obj.GetCanLocation();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCanVoice(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			int o = obj.GetCanVoice();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCanCamera(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			int o = obj.GetCanCamera(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCanPushNotification(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			int o = obj.GetCanPushNotification();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OpenLocation(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			obj.OpenLocation();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OpenVoice(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			obj.OpenVoice();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OpenCamera(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			obj.OpenCamera();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GotoSetScene(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.GotoSetScene(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadFile(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			byte[] o = obj.LoadFile(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ForceQuit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			obj.ForceQuit();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GGInit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.GGInit(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddGoogleComCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.AddGoogleComCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddSkuStateFromPurchaseCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.AddSkuStateFromPurchaseCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddOnGGBuyResultCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.AddOnGGBuyResultCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GGBuy(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.GGBuy(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGGConsumeInappPurchase(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OnGGConsumeInappPurchase(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGGRefreshPurchasesAsync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OnGGRefreshPurchasesAsync(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGGQuerySkuDetailsAsync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OnGGQuerySkuDetailsAsync(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGGIsReady(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			bool o = obj.OnGGIsReady();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGGConnection(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			obj.OnGGConnection();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGGIsPurchased(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.OnGGIsPurchased(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGGCanPurchased(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.OnGGCanPurchased(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGGBillingFlowInProcess(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.OnGGBillingFlowInProcess(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGGSkuTitle(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string o = obj.OnGGSkuTitle(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGGSkuPrice(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string o = obj.OnGGSkuPrice(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGGSkuDescription(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string o = obj.OnGGSkuDescription(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGGLogEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OnGGLogEvent(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGGReview(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OnGGReview(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGGLaunchReview(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OnGGLaunchReview(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGGSignIn(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.OnGGSignIn(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGGSignOut(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.OnGGSignOut(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGGRevokeAccess(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.OnGGRevokeAccess(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAFConversionJsonData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string o = obj.GetAFConversionJsonData(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddOnAFConversionCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.AddOnAFConversionCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnAFInit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.OnAFInit(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnAFStart(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.OnAFStart(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnAFLogEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OnAFLogEvent(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMessagingData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.GetMessagingData(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddFirebaseComCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.AddFirebaseComCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnSubscribeToTopic(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OnSubscribeToTopic(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnUnsubscribeFromTopic(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.OnUnsubscribeFromTopic(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendUpstream(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaFramework.SDKManager obj = (LuaFramework.SDKManager)ToLua.CheckObject<LuaFramework.SDKManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SendUpstream(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

