return {
	config=
	{
		[1]=
		{
			id = 1,
			show_type = 1,
			bq_id = 1,
			type = 1,
			perm = 0,
		},
		[2]=
		{
			id = 2,
			show_type = 1,
			bq_id = 2,
			type = 1,
			perm = 0,
		},
		[3]=
		{
			id = 3,
			show_type = 1,
			bq_id = 3,
			type = 1,
			perm = 0,
		},
		[4]=
		{
			id = 4,
			show_type = 1,
			bq_id = 4,
			type = 1,
			perm = 3,
			item_key = "prop_emoji_mgh",
		},
		[5]=
		{
			id = 5,
			show_type = 1,
			bq_id = 5,
			type = 1,
			perm = 5,
			item_key = "prop_emoji_xmc",
		},
		[6]=
		{
			id = 6,
			show_type = 1,
			bq_id = 6,
			type = 1,
			perm = 8,
			item_key = "prop_emoji_fw",
		},
		[7]=
		{
			id = 7,
			show_type = 1,
			bq_id = 7,
			type = 1,
			perm = 10,
			item_key = "prop_emoji_cp",
		},
		[8]=
		{
			id = 8,
			show_type = 1,
			bq_id = 8,
			type = 2,
			perm = 1,
			item_key = "prop_emoji_xhs",
		},
		[9]=
		{
			id = 9,
			show_type = 1,
			bq_id = 9,
			type = 2,
			perm = 1,
			item_key = "prop_emoji_pj",
		},
		[10]=
		{
			id = 10,
			show_type = 1,
			bq_id = 10,
			type = 2,
			perm = 1,
			item_key = "prop_emoji_ax",
		},
		[11]=
		{
			id = 11,
			show_type = 1,
			bq_id = 11,
			type = 2,
			perm = 2,
			item_key = "prop_emoji_ll",
		},
		[12]=
		{
			id = 12,
			show_type = 1,
			bq_id = 12,
			type = 2,
			perm = 2,
			item_key = "prop_emoji_jz",
		},
		[13]=
		{
			id = 13,
			show_type = 1,
			bq_id = 13,
			type = 2,
			perm = 3,
			item_key = "prop_emoji_zj",
		},
		[14]=
		{
			id = 14,
			show_type = 1,
			bq_id = 14,
			type = 2,
			perm = 3,
			item_key = "prop_emoji_sd",
		},
		[15]=
		{
			id = 15,
			show_type = 2,
			bq_id = 15,
			type = 1,
			perm = 0,
		},
		[16]=
		{
			id = 16,
			show_type = 2,
			bq_id = 16,
			type = 1,
			perm = 0,
		},
		[17]=
		{
			id = 17,
			show_type = 2,
			bq_id = 17,
			type = 1,
			perm = 0,
		},
		[18]=
		{
			id = 18,
			show_type = 2,
			bq_id = 18,
			type = 1,
			perm = 0,
		},
		[19]=
		{
			id = 19,
			show_type = 2,
			bq_id = 19,
			type = 1,
			perm = 0,
		},
		[20]=
		{
			id = 20,
			show_type = 2,
			bq_id = 20,
			type = 1,
			perm = 0,
		},
		[21]=
		{
			id = 21,
			show_type = 2,
			bq_id = 21,
			type = 1,
			perm = 0,
		},
		[22]=
		{
			id = 22,
			show_type = 2,
			bq_id = 22,
			type = 1,
			perm = 0,
		},
		[23]=
		{
			id = 23,
			show_type = 2,
			bq_id = 23,
			type = 1,
			perm = 0,
		},
		[24]=
		{
			id = 24,
			show_type = 3,
			bq_id = 24,
			type = 1,
			perm = 0,
		},
		[25]=
		{
			id = 25,
			show_type = 3,
			bq_id = 25,
			type = 1,
			perm = 0,
		},
		[26]=
		{
			id = 26,
			show_type = 3,
			bq_id = 26,
			type = 1,
			perm = 0,
		},
		[27]=
		{
			id = 27,
			show_type = 3,
			bq_id = 27,
			type = 1,
			perm = 0,
		},
		[28]=
		{
			id = 28,
			show_type = 3,
			bq_id = 28,
			type = 1,
			perm = 0,
		},
		[29]=
		{
			id = 29,
			show_type = 3,
			bq_id = 29,
			type = 1,
			perm = 0,
		},
		[30]=
		{
			id = 30,
			show_type = 3,
			bq_id = 30,
			type = 2,
			perm = 0,
		},
		[31]=
		{
			id = 31,
			show_type = 3,
			bq_id = 31,
			type = 2,
			perm = 0,
		},
		[32]=
		{
			id = 32,
			show_type = 3,
			bq_id = 32,
			type = 2,
			perm = 0,
		},
	},
	bq=
	{
		[1]=
		{
			line = 1,
			id = 1,
			sex = 1,
			name = "拍手",
			audio = "brow_ps.mp3",
			prefab = "BQ_paishou",
			icon = "bqxt_011",
			mood_type = 1,
			show_time = 2,
		},
		[2]=
		{
			line = 2,
			id = 1,
			sex = 0,
			name = "拍手",
			audio = "brow_ps.mp3",
			prefab = "BQ_paishou",
			icon = "bqxt_011",
			mood_type = 1,
			show_time = 2,
		},
		[3]=
		{
			line = 3,
			id = 2,
			sex = 1,
			name = "拖鞋",
			audio = "brow_tx.mp3",
			move_prefab = "BQ_tuoxie_01",
			prefab = "BQ_tuoxie_02",
			icon = "bqxt_014",
			mood_type = 1,
			show_time = 2,
		},
		[4]=
		{
			line = 4,
			id = 2,
			sex = 0,
			name = "拖鞋",
			audio = "brow_tx.mp3",
			move_prefab = "BQ_tuoxie_01",
			prefab = "BQ_tuoxie_02",
			icon = "bqxt_014",
			mood_type = 1,
			show_time = 2,
		},
		[5]=
		{
			line = 5,
			id = 3,
			sex = 1,
			name = "鸡蛋",
			audio = "brow_jd.mp3",
			move_prefab = "BQ_jidan_01",
			prefab = "BQ_jidan_02",
			icon = "bqxt_01",
			mood_type = 1,
			show_time = 2,
		},
		[6]=
		{
			line = 6,
			id = 3,
			sex = 0,
			name = "鸡蛋",
			audio = "brow_jd.mp3",
			move_prefab = "BQ_jidan_01",
			prefab = "BQ_jidan_02",
			icon = "bqxt_01",
			mood_type = 1,
			show_time = 2,
		},
		[7]=
		{
			line = 7,
			id = 4,
			sex = 1,
			name = "玫瑰花",
			audio = "brow_mgh.mp3",
			move_prefab = "BQ_meiguihua_02",
			prefab = "BQ_meiguihua",
			icon = "bqxt_012",
			mood_type = 1,
			show_time = 2,
		},
		[8]=
		{
			line = 8,
			id = 4,
			sex = 0,
			name = "玫瑰花",
			audio = "brow_mgh.mp3",
			move_prefab = "BQ_meiguihua_02",
			prefab = "BQ_meiguihua",
			icon = "bqxt_012",
			mood_type = 1,
			show_time = 2,
		},
		[9]=
		{
			line = 9,
			id = 5,
			sex = 1,
			name = "木槌",
			audio = "brow_mc.mp3",
			move_prefab = "BQ_muchui_01",
			prefab = "BQ_muchui_02",
			icon = "bqxt_05",
			mood_type = 1,
			show_time = 2,
		},
		[10]=
		{
			line = 10,
			id = 5,
			sex = 0,
			name = "木槌",
			audio = "brow_mc.mp3",
			move_prefab = "BQ_muchui_01",
			prefab = "BQ_muchui_02",
			icon = "bqxt_05",
			mood_type = 1,
			show_time = 2,
		},
		[11]=
		{
			line = 11,
			id = 6,
			sex = 1,
			name = "亲嘴",
			audio = "brow_fw.mp3",
			move_prefab = "BQ_qinqin_02",
			prefab = "BQ_qinqin",
			icon = "bqxt_08",
			mood_type = 1,
			show_time = 2,
		},
		[12]=
		{
			line = 12,
			id = 6,
			sex = 0,
			name = "亲嘴",
			audio = "brow_fw.mp3",
			move_prefab = "BQ_qinqin_02",
			prefab = "BQ_qinqin",
			icon = "bqxt_08",
			mood_type = 1,
			show_time = 2,
		},
		[13]=
		{
			line = 13,
			id = 7,
			sex = 1,
			name = "钞票",
			audio = "brow_cp.mp3",
			move_prefab = "BQ_qian",
			prefab = "BQ_qian_02",
			icon = "bqxt_010",
			mood_type = 1,
			show_time = 2,
		},
		[14]=
		{
			line = 14,
			id = 7,
			sex = 0,
			name = "钞票",
			audio = "brow_cp.mp3",
			move_prefab = "BQ_qian",
			prefab = "BQ_qian_02",
			icon = "bqxt_010",
			mood_type = 1,
			show_time = 2,
		},
		[15]=
		{
			line = 15,
			id = 8,
			sex = 1,
			name = "西红柿",
			audio = "brow_xhs.mp3",
			move_prefab = "BQ_xhs_01",
			prefab = "BQ_xhs_02",
			icon = "bqxt_04",
			mood_type = 1,
			show_time = 2,
		},
		[16]=
		{
			line = 16,
			id = 8,
			sex = 0,
			name = "西红柿",
			audio = "brow_xhs.mp3",
			move_prefab = "BQ_xhs_01",
			prefab = "BQ_xhs_02",
			icon = "bqxt_04",
			mood_type = 1,
			show_time = 2,
		},
		[17]=
		{
			line = 17,
			id = 9,
			sex = 1,
			name = "啤酒",
			audio = "brow_pj.mp3",
			move_prefab = "BQ_pijiu_01",
			prefab = "BQ_pijiu_02",
			icon = "bqxt_06",
			mood_type = 1,
			show_time = 2,
		},
		[18]=
		{
			line = 18,
			id = 9,
			sex = 0,
			name = "啤酒",
			audio = "brow_pj.mp3",
			move_prefab = "BQ_pijiu_01",
			prefab = "BQ_pijiu_02",
			icon = "bqxt_06",
			mood_type = 1,
			show_time = 2,
		},
		[19]=
		{
			line = 19,
			id = 10,
			sex = 1,
			name = "爱心",
			audio = "brow_ax.mp3",
			move_prefab = "BQ_aixin_01",
			prefab = "BQ_aixin_02",
			icon = "bqxt_02",
			mood_type = 1,
			show_time = 2,
		},
		[20]=
		{
			line = 20,
			id = 10,
			sex = 0,
			name = "爱心",
			audio = "brow_ax.mp3",
			move_prefab = "BQ_aixin_01",
			prefab = "BQ_aixin_02",
			icon = "bqxt_02",
			mood_type = 1,
			show_time = 2,
		},
		[21]=
		{
			line = 21,
			id = 11,
			sex = 1,
			name = "榴莲",
			audio = "brow_ll.mp3",
			move_prefab = "BQ_liulian_zhuan",
			prefab = "BQ_liulian",
			icon = "bqxt_09",
			mood_type = 1,
			show_time = 2,
		},
		[22]=
		{
			line = 22,
			id = 11,
			sex = 0,
			name = "榴莲",
			audio = "brow_ll.mp3",
			move_prefab = "BQ_liulian_zhuan",
			prefab = "BQ_liulian",
			icon = "bqxt_09",
			mood_type = 1,
			show_time = 2,
		},
		[23]=
		{
			line = 23,
			id = 12,
			sex = 1,
			name = "金砖",
			audio = "brow_jz.mp3",
			prefab = "BQ_jinzhuan",
			icon = "bqxt_03",
			mood_type = 1,
			show_time = 2,
		},
		[24]=
		{
			line = 24,
			id = 12,
			sex = 0,
			name = "金砖",
			audio = "brow_jz.mp3",
			prefab = "BQ_jinzhuan",
			icon = "bqxt_03",
			mood_type = 1,
			show_time = 2,
		},
		[25]=
		{
			line = 25,
			id = 13,
			sex = 1,
			name = "钻戒",
			audio = "brow_zj.mp3",
			move_prefab = "BQ_jiezhi_01",
			prefab = "BQ_jiezhi_02",
			icon = "bqxt_07",
			mood_type = 1,
			show_time = 2,
		},
		[26]=
		{
			line = 26,
			id = 13,
			sex = 0,
			name = "钻戒",
			audio = "brow_zj.mp3",
			move_prefab = "BQ_jiezhi_01",
			prefab = "BQ_jiezhi_02",
			icon = "bqxt_07",
			mood_type = 1,
			show_time = 2,
		},
		[27]=
		{
			line = 27,
			id = 14,
			sex = 1,
			name = "闪电",
			audio = "brow_sd.mp3",
			prefab = "BQ_shandian",
			icon = "bqxt_013",
			mood_type = 1,
			show_time = 2,
		},
		[28]=
		{
			line = 28,
			id = 14,
			sex = 0,
			name = "闪电",
			audio = "brow_sd.mp3",
			prefab = "BQ_shandian",
			icon = "bqxt_013",
			mood_type = 1,
			show_time = 2,
		},
		[29]=
		{
			line = 29,
			id = 15,
			sex = 1,
			name = "你好",
			desc = "Halo!",
			mood_type = 1,
			show_time = 2,
		},
		[30]=
		{
			line = 30,
			id = 15,
			sex = 0,
			name = "你好",
			desc = "Halo!",
			mood_type = 1,
			show_time = 2,
		},
		[31]=
		{
			line = 31,
			id = 16,
			sex = 1,
			name = "你怎么能赢呢？",
			desc = "Begini juga bisa menang kok?",
			mood_type = 1,
			show_time = 2,
		},
		[32]=
		{
			line = 32,
			id = 16,
			sex = 0,
			name = "你怎么能赢呢？",
			desc = "Begini juga bisa menang kok?",
			mood_type = 1,
			show_time = 2,
		},
		[33]=
		{
			line = 33,
			id = 17,
			sex = 1,
			name = "位置不太好！",
			desc = "Posisi kurang bagus!",
			mood_type = 1,
			show_time = 2,
		},
		[34]=
		{
			line = 34,
			id = 17,
			sex = 0,
			name = "位置不太好！",
			desc = "Posisi kurang bagus!",
			mood_type = 1,
			show_time = 2,
		},
		[35]=
		{
			line = 35,
			id = 18,
			sex = 1,
			name = "快点！",
			desc = "Ayo cepat!",
			mood_type = 1,
			show_time = 2,
		},
		[36]=
		{
			line = 36,
			id = 18,
			sex = 0,
			name = "快点！",
			desc = "Ayo cepat!",
			mood_type = 1,
			show_time = 2,
		},
		[37]=
		{
			line = 37,
			id = 19,
			sex = 1,
			name = "我的牌太难看了！",
			desc = "Kartu saya terlalu jelek!",
			mood_type = 1,
			show_time = 2,
		},
		[38]=
		{
			line = 38,
			id = 19,
			sex = 0,
			name = "我的牌太难看了！",
			desc = "Kartu saya terlalu jelek!",
			mood_type = 1,
			show_time = 2,
		},
		[39]=
		{
			line = 39,
			id = 20,
			sex = 1,
			name = "你的牌真棒！",
			desc = "Kartu Anda luar biasa!",
			mood_type = 1,
			show_time = 2,
		},
		[40]=
		{
			line = 40,
			id = 20,
			sex = 0,
			name = "你的牌真棒！",
			desc = "Kartu Anda luar biasa!",
			mood_type = 1,
			show_time = 2,
		},
		[41]=
		{
			line = 41,
			id = 21,
			sex = 1,
			name = "再给我一个！",
			desc = "Biarkan aku keluarkan 1 lagi!",
			mood_type = 1,
			show_time = 2,
		},
		[42]=
		{
			line = 42,
			id = 21,
			sex = 0,
			name = "再给我一个！",
			desc = "Biarkan aku keluarkan 1 lagi!",
			mood_type = 1,
			show_time = 2,
		},
		[43]=
		{
			line = 43,
			id = 22,
			sex = 1,
			name = "有意思！",
			desc = "Menarik!",
			mood_type = 1,
			show_time = 2,
		},
		[44]=
		{
			line = 44,
			id = 22,
			sex = 0,
			name = "有意思！",
			desc = "Menarik!",
			mood_type = 1,
			show_time = 2,
		},
		[45]=
		{
			line = 45,
			id = 23,
			sex = 1,
			name = "好牌！",
			desc = "Kartu yang bagus!",
			mood_type = 1,
			show_time = 2,
		},
		[46]=
		{
			line = 46,
			id = 23,
			sex = 0,
			name = "好牌！",
			desc = "Kartu yang bagus!",
			mood_type = 1,
			show_time = 2,
		},
		[47]=
		{
			line = 47,
			id = 24,
			sex = 1,
			name = "高兴",
			prefab = "BQ_gaoxin",
			icon = "tou_01",
			desc = "高兴",
			mood_type = 1,
			show_time = 2,
		},
		[48]=
		{
			line = 48,
			id = 24,
			sex = 0,
			name = "高兴",
			prefab = "BQ_gaoxin",
			icon = "tou_01",
			desc = "高兴",
			mood_type = 1,
			show_time = 2,
		},
		[49]=
		{
			line = 49,
			id = 25,
			sex = 1,
			name = "哭泣",
			prefab = "BQ_daku",
			icon = "ku_02",
			desc = "哭泣",
			mood_type = 2,
			show_time = 2,
		},
		[50]=
		{
			line = 50,
			id = 25,
			sex = 0,
			name = "哭泣",
			prefab = "BQ_daku",
			icon = "ku_02",
			desc = "哭泣",
			mood_type = 2,
			show_time = 2,
		},
		[51]=
		{
			line = 51,
			id = 26,
			sex = 1,
			name = "坏笑",
			prefab = "BQ_huaixiao",
			icon = "tou_03",
			desc = "坏笑",
			mood_type = 2,
			show_time = 2,
		},
		[52]=
		{
			line = 52,
			id = 26,
			sex = 0,
			name = "坏笑",
			prefab = "BQ_huaixiao",
			icon = "tou_03",
			desc = "坏笑",
			mood_type = 2,
			show_time = 2,
		},
		[53]=
		{
			line = 53,
			id = 27,
			sex = 1,
			name = "激动",
			prefab = "BQ_jidong",
			icon = "tou_06",
			desc = "激动",
			mood_type = 2,
			show_time = 2,
		},
		[54]=
		{
			line = 54,
			id = 27,
			sex = 0,
			name = "激动",
			prefab = "BQ_jidong",
			icon = "tou_06",
			desc = "激动",
			mood_type = 2,
			show_time = 2,
		},
		[55]=
		{
			line = 55,
			id = 28,
			sex = 1,
			name = "惊讶",
			prefab = "BQ_jinya",
			icon = "tou_02",
			desc = "惊讶",
			mood_type = 2,
			show_time = 2,
		},
		[56]=
		{
			line = 56,
			id = 28,
			sex = 0,
			name = "惊讶",
			prefab = "BQ_jinya",
			icon = "tou_02",
			desc = "惊讶",
			mood_type = 2,
			show_time = 2,
		},
		[57]=
		{
			line = 57,
			id = 29,
			sex = 1,
			name = "开心",
			prefab = "BQ_kaixin",
			icon = "tou_09",
			desc = "开心",
			mood_type = 2,
			show_time = 2,
		},
		[58]=
		{
			line = 58,
			id = 29,
			sex = 0,
			name = "开心",
			prefab = "BQ_kaixin",
			icon = "tou_09",
			desc = "开心",
			mood_type = 2,
			show_time = 2,
		},
		[59]=
		{
			line = 59,
			id = 30,
			sex = 1,
			name = "生气",
			prefab = "BQ_shengqi",
			icon = "tou_07",
			desc = "生气",
			mood_type = 2,
			show_time = 2,
		},
		[60]=
		{
			line = 60,
			id = 30,
			sex = 0,
			name = "生气",
			prefab = "BQ_shengqi",
			icon = "tou_07",
			desc = "生气",
			mood_type = 2,
			show_time = 2,
		},
		[61]=
		{
			line = 61,
			id = 31,
			sex = 1,
			name = "睡觉",
			prefab = "BQ_shuijiao",
			icon = "tou_04",
			desc = "睡觉",
			mood_type = 2,
			show_time = 2,
		},
		[62]=
		{
			line = 62,
			id = 31,
			sex = 0,
			name = "睡觉",
			prefab = "BQ_shuijiao",
			icon = "tou_04",
			desc = "睡觉",
			mood_type = 2,
			show_time = 2,
		},
		[63]=
		{
			line = 63,
			id = 32,
			sex = 1,
			name = "郁闷",
			prefab = "BQ_yumen",
			icon = "tou_08",
			desc = "郁闷",
			mood_type = 2,
			show_time = 2,
		},
		[64]=
		{
			line = 64,
			id = 32,
			sex = 0,
			name = "郁闷",
			prefab = "BQ_yumen",
			icon = "tou_08",
			desc = "郁闷",
			mood_type = 2,
			show_time = 2,
		},
	},
}